### ISSUE TITLE
Можно отправить пустую форму

### ISSUE THREAD

**Issue by dfitiskin** [evilHoms/coopDraw#2]
По ТЗ не понятно какие из полей обязательные, но я думаю что как минимум имя должно быть обязательным.

**Comment by dfitiskin** [comment]
Все еще можно отправить пустую форму. Ошибка показывается уже после отправки. Идея в том, чтобы заблокировать кнопку отправки, пока не введено имя

**Comment by dfitiskin** [comment]
Кнопка «submit» должна быть заблокирована.

**Comment by evilHoms** [comment]
Она заблокирована. Запрос на ней не обрабатывается при пустом поле "name" ни при клике, ни при нажатии на enter. Поле password при этом не проверяется, тк пароля может не быть.
